[package]
name = "supernote-tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"
eframe = "0.28.1"
egui = "0.28.1"
regex = "1.10.3"
serde = {version = "1.0.195", features = ["derive"]}
serde_json = "1.0.111"
vtracer = "0.6.3"
