[package]
name = "supernote-tool"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"
eframe = "0.28.1"
egui = "0.28.1"
libc = "0.2.158"
lopdf = "0.34.0"
regex = "1.10.3"
rfd = "0.15.0"
serde = {version = "1.0.195", features = ["derive"]}
serde_json = "1.0.111"

[build-dependencies]
bindgen = "0.70.1"
